### ISSUE TITLE
Is Tensorflow required?

### ISSUE THREAD

**Issue by slaweks17** [damitkwr/ESRNN-GPU#11]
You import it in logger.py

**Comment by damitkwr** [comment]
Yeah, we were using it for Tensorboard logging functions.

**Comment by slaweks17** [comment]
Them please update the list of requirements. Would TF2 Beta be OK?

**Comment by damitkwr** [comment]
Just tried running it with TF2.0, we can refactor the code when TF comes out of beta but I am updating it to include TF 1.13

**Comment by slaweks17** [comment]
Thank you. OK, I will try TF2 Beta, if I have problems I will switch to 1.13
