### ISSUE TITLE
Questions/Clarifications on ESRNN-GPU vs original ES-RNN

### ISSUE THREAD

**Issue by tjphilpot** [damitkwr/ESRNN-GPU#14]
Great work on this project! Having used a version of the original ES-RNN code, I have a few questions about the differences between the implementations and the results presented in the paper.

1. The paper mentions "Note that for monthly data, Smyl et al. (2018) were running the algorithm of 6 pairs of 2 workers and for quarterly data, 4 pairs of 2 workers were used." For the results, did the times reported in the paper represent running the ESRNN-GPU implementation with multiple workers in aggregate (CPU Time), multiple workers concurrently (Wall Clock Time) or was the time reported for a single worker?

2. What GPU did you test on? Testing the M4 data set with CUDA enabled PyTorch on a notebook graphics cards (Nvidia GeForce GTX 1050) vs non-CUDA enabled PyTorch showed the CPU only version to be faster (i7 8550) by about 3x. It is likely that the PyTorch CPU enabled version is still faster the the original ESRNN, but I have not confirmed that.

3. Is there any plan to implemented the future work for Variable Length Series mentioned in Section 8.1? What would be required?

**Comment by damitkwr** [comment]
1.  We reported the Wall Clock time as we asked Smyl directly for the time
2. We used a 1080Ti and to increase the run time, increase the batch size. I believe we ran the sizes near a thousand or so
3. Variable length implementation would require us to use dynamic RNNs and masking for the different loss. It takes some work but we plan to add that functionality in the coming months.

**Comment by damitkwr** [comment]
To actually better answer Question 2, the PyTorch CPU version will still be a lot faster than the original C++ implementation. PyTorch allows us to use parallelism in the way the computations are being done. If you look at the original paper, Slawek originally used a pseudo parameter server strategy where each core is working on some time series and the main parameters are being stored on a text file on the main server. It is updated as each of the workers finishes their jobs. Think of the CUDA cores on the GPU as smaller but faster cores and with the parameters being loaded & updated in-memory, you can see where the speed-ups come from.
