### ISSUE TITLE
ModuleNotFoundError: No module named 'ESRNN.m4_data'; 'ESRNN' is not a package

### ISSUE THREAD

**Issue by frenchmatthew** [damitkwr/ESRNN-GPU#22]
Hello, 

I've tried to install ESRNN via the instruction in this link: https://pypi.org/project/ESRNN/ 
which were: pip install ESRNN

However, when I try to run the follow code: 

from ESRNN.m4_data import prepare_m4_data
from ESRNN.utils_evaluation import evaluate_prediction_owa

from ESRNN import ESRNN

I get the following error: 

Traceback (most recent call last):
  File "ESRNN.py", line 2, in <module>
    from ESRNN.m4_data import prepare_m4_data
  File "C:\Users\mario\Documents\Python Benjamin\ESRNN.py", line 2, in <module>
    from ESRNN.m4_data import prepare_m4_data
ModuleNotFoundError: No module named 'ESRNN.m4_data'; 'ESRNN' is not a package

I've tried adding ESRNN as a path variable and still get the same error. 

Could anyone please assist?

**Comment by dan-r95** [comment]
I moved the main file out of the `es_rnn` folder
then the import worked
