### ISSUE TITLE
es_rnn module not found error 

### ISSUE THREAD

**Issue by 12suyash** [damitkwr/ESRNN-GPU#6]
when i run the code in pthon es_rnn module not found occurs shows

**Comment by damitkwr** [comment]
Did you add the project path in your PYTHON path when you ran it?

**Comment by 12suyash** [comment]
i have a problem in installing i type pip install git+https://github.com/damitkwr/ESRNN-GPU.git then error occurs then i type pip install git+https://github.com/damitkwr/ESRNN-GPU.git#egg=ESRNN-GPU then also error show plz help
