### ISSUE TITLE
issue in upacking the project

### ISSUE THREAD

**Issue by 12suyash** [damitkwr/ESRNN-GPU#7]
i have a problem in installing i type pip install git+https://github.com/damitkwr/ESRNN-GPU.git then error occurs then i type pip install git+https://github.com/damitkwr/ESRNN-GPU.git#egg=ESRNN-GPU then also error show plz help

**Comment by damitkwr** [comment]
Hi,

This is not a python package. Rather it is just an implementation. Add the es-rnn folder to Python system path.

**Comment by 12suyash** [comment]
thanks
