### ISSUE TITLE
What is info.csv in es-rnn(main.py)?

### ISSUE THREAD

**Issue by donovanfan** [damitkwr/ESRNN-GPU#8]
Hi,
I am trying to use the code, but I encounter several issues. One is that, 
"train_path = '../data/Train/%s-train.csv' % (config['variable'])
test_path = '../data/Test/%s-test.csv' % (config['variable'])"
in main.py cause some problems. If I understand the code correctly, it changes the path to "../data/Train/Daily-train.csv", which is a CSV file that does not exist. The other issue is that I do not really understand what kind of information info.csv should contain. Would you please help me deal with these problems?
Thanks

**Comment by damitkwr** [comment]
These are the paths for the M4 dataset. I don't think we are allowed to share the M4 competition dataset but you can easily sign the agreement and get the dataset at [this url](https://www.mcompetitions.unic.ac.cy/the-dataset/)
